from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class StrategySpec:
    key: str
    family: str
    markets: tuple[str, ...]
    status: str
    hypothesis: str
    main_risks: tuple[str, ...]


def _s(key, family, markets, status, hypothesis, *risks):
    return StrategySpec(key, family, tuple(markets), status, hypothesis, tuple(risks))


CATALOG = (
    _s("buy_hold", "benchmark", ["all"], "implemented", "Risk-premium benchmark", "drawdown"),
    _s(
        "ma_cross",
        "trend",
        ["kr_etf", "crypto"],
        "implemented",
        "Persistent moves continue",
        "whipsaw",
    ),
    _s(
        "donchian",
        "trend",
        ["kr_etf", "crypto"],
        "implemented",
        "New extremes identify trends",
        "false breakout",
    ),
    _s(
        "ts_momentum",
        "trend",
        ["kr_etf", "crypto"],
        "implemented",
        "Own past return predicts direction",
        "momentum crash",
    ),
    _s(
        "cross_sectional_momentum",
        "momentum",
        ["kr_equity", "crypto"],
        "implemented",
        "Winners outperform losers",
        "crash",
        "turnover",
    ),
    _s(
        "dual_momentum",
        "momentum",
        ["kr_etf"],
        "implemented",
        "Combine absolute and relative momentum",
        "regime shift",
    ),
    _s(
        "rsi_reversion",
        "mean_reversion",
        ["kr_equity", "crypto"],
        "implemented",
        "Short shocks partially reverse",
        "trend loss",
    ),
    _s(
        "bollinger_reversion",
        "mean_reversion",
        ["all"],
        "implemented",
        "Large z-score deviations revert",
        "structural break",
    ),
    _s(
        "overnight_gap_fade",
        "mean_reversion",
        ["kr_equity"],
        "implemented",
        "Large opening gaps partially close",
        "news gap",
    ),
    _s(
        "pairs_distance",
        "stat_arb",
        ["kr_equity", "crypto"],
        "implemented",
        "Close substitutes temporarily diverge",
        "pair break",
    ),
    _s(
        "cointegration_spread",
        "stat_arb",
        ["kr_equity", "crypto"],
        "planned",
        "Stable linear combinations mean-revert",
        "lookahead",
        "break",
    ),
    _s(
        "pca_residual",
        "stat_arb",
        ["kr_equity", "crypto"],
        "planned",
        "Idiosyncratic residuals revert",
        "crowding",
    ),
    _s(
        "volatility_breakout",
        "breakout",
        ["kr_equity", "crypto"],
        "implemented",
        "Range expansion continues intraday",
        "gap",
        "slippage",
    ),
    _s(
        "volume_momentum",
        "microstructure",
        ["all"],
        "implemented",
        "Volume confirms informed moves",
        "volume anomaly",
    ),
    _s(
        "vwap_reversion",
        "microstructure",
        ["kr_equity", "crypto"],
        "planned",
        "Intraday price returns toward VWAP",
        "adverse selection",
    ),
    _s(
        "orderbook_imbalance",
        "microstructure",
        ["crypto"],
        "planned",
        "Queue imbalance predicts short returns",
        "latency",
    ),
    _s(
        "market_making",
        "market_making",
        ["crypto"],
        "planned",
        "Earn spread while controlling inventory",
        "adverse selection",
        "latency",
    ),
    _s(
        "listing_reversal",
        "event",
        ["crypto"],
        "planned",
        "Post-listing excess reverses",
        "liquidity",
        "selection bias",
    ),
    _s(
        "earnings_drift",
        "event",
        ["kr_equity"],
        "planned",
        "Markets underreact to earnings surprise",
        "data timing",
    ),
    _s(
        "index_rebalance",
        "event",
        ["kr_equity"],
        "planned",
        "Forced index flows affect prices",
        "announcement leakage",
    ),
    _s(
        "funding_carry",
        "carry",
        ["crypto"],
        "implemented",
        "Hedged shorts collect positive funding",
        "basis",
        "venue",
    ),
    _s(
        "cross_venue_funding",
        "carry",
        ["crypto"],
        "planned",
        "Funding differs across venues",
        "leg risk",
        "transfer",
    ),
    _s(
        "cash_and_carry",
        "carry",
        ["crypto"],
        "planned",
        "Futures premium converges to spot",
        "margin",
        "custody",
    ),
    _s(
        "kimchi_premium",
        "arbitrage",
        ["crypto"],
        "research_only",
        "KRW and offshore prices diverge",
        "capital controls",
        "transfer",
    ),
    _s(
        "triangular_arbitrage",
        "arbitrage",
        ["crypto"],
        "planned",
        "Three pairs violate parity briefly",
        "latency",
        "partial fill",
    ),
    _s(
        "cross_exchange_spread",
        "arbitrage",
        ["crypto"],
        "planned",
        "Same asset trades at different prices",
        "inventory",
        "venue",
    ),
    _s(
        "low_volatility",
        "factor",
        ["kr_equity"],
        "planned",
        "Low-risk stocks offer superior risk-adjusted returns",
        "crowding",
    ),
    _s(
        "value_quality",
        "factor",
        ["kr_equity"],
        "planned",
        "Cheap profitable firms outperform",
        "fundamental lag",
    ),
    _s(
        "small_cap",
        "factor",
        ["kr_equity"],
        "planned",
        "Smaller firms carry a premium",
        "liquidity",
    ),
    _s(
        "risk_parity",
        "allocation",
        ["kr_etf", "crypto"],
        "implemented",
        "Balance risk rather than capital",
        "correlation spike",
    ),
    _s(
        "volatility_target",
        "allocation",
        ["all"],
        "implemented",
        "Scale exposure to stable risk",
        "vol forecast",
    ),
    _s(
        "trend_reversion_ensemble",
        "ensemble",
        ["all"],
        "planned",
        "Diversify signals across regimes",
        "hidden correlation",
    ),
    _s(
        "regime_switching",
        "ensemble",
        ["all"],
        "planned",
        "Signal efficacy changes by regime",
        "overfitting",
    ),
    _s(
        "supervised_return_rank",
        "machine_learning",
        ["all"],
        "research_only",
        "Features rank future returns",
        "leakage",
        "decay",
    ),
    _s(
        "reinforcement_learning",
        "machine_learning",
        ["all"],
        "research_only",
        "Agent learns execution/policy",
        "simulation gap",
    ),
)
